### PR TITLE
Minimal Weather App 🌤 - Sofia Vaz Sousa 

### PR DESCRIPTION
**Pull request by sofiavazs**
**Link to my deployed project:**
https://minimalweatherapp.netlify.app/

**My reflections on how this week's project turned out:**
I'm really happy with how the project turned out and that I managed to achieve the red level as well as some from the black level and was really awesome to work with API's.
 I'm also glad that I made it responsive and with an option of few cities. 
I started this project by extracting all the data I needed from the Open Weather and the Ultraviolet Index API's 
Then I coded my way into displaying it all in a blank page and then did the styling, which was really interesting as I learned to inject items directly from javascript and managed to change background colours (from a cool toned gradient to a warm toned one) depending on the current temperature or the time of the day - wait until it reaches 18 degrees celsius or be night time to see the magic happen! 🔮

**Things I'd like to have clarified or explained in more detail:**

I ran into a problem while dealing with the min and max temperatures for the 5 day forecast since it has a 3 hour interval (due to the how the API is made) and choosing a specific hour in the middle of the day (using the hint given in the brief) would bring too little variation, but I managed with help to deal with it in a way that it will compare the temperatures and display the lowest temperature for the day and do the same for the highest, but even though I grasp the concept I still feel like I would not know how to do it from memory again if I needed to and I feel it was quite advanced, so maybe it would be nice to get more practice in this kind of scenarios. 

Thank you!

### CODE REVIEW

**Review by sandra-shumanteva-kaevska — APPROVED** [review]
Awesome work. really clean and readable code. Well structured and nice looking project. 💯 I am proud of you :)

**Review by EmOlsz — CHANGES_REQUESTED** [review]
Great job Sofia :) You've done pretty advanced project this week! We have a lot of different cities to show, each one of them will also change way your data is presented in app. Congrats!
Apart from that, I see some bad habits that start to arise in your flow (they are minor, nonetheless for recruiter on code reviewer in future they might be crucial) - please, take a look on my comments and adjust your code to them. After that, I'll be able to approve you project

**Comment by sofiavazs** [comment]
Hi Maks! 
Thanks for the code review, I've made changes to my code according to your review. 
I know indentation has been one of my (many) weaknesses so I've been paying more attention to it lately. And styling by id's was one of my fall backs when I got introduced to javascript, which I'm also avoiding to use it altogether since understanding it more and more. 

Hope the changes are okay, otherwise let me know :)

**Comment by EmOlsz** [comment]
> Hi Maks!
> Thanks for the code review, I've made changes to my code according to your review.
> I know indentation has been one of my (many) weaknesses so I've been paying more attention to it lately. And styling by id's was one of my fall backs when I got introduced to javascript, which I'm also avoiding to use it altogether since understanding it more and more.
> 
> Hope the changes are okay, otherwise let me know :)

Hey Sofia, thanks for your updates! Yes, everything is ok right now :) Moreover, it's completely understandable that you find it hard to keep everything correct in your code - there is just too much knowledge to keep during such short period. That's why we have code reviews, no worries :)
Project approved

**Review by EmOlsz — APPROVED** [review]

**Pull request closed without merging**
